---
title: "04_GSEA analysis"
author: "Nick Diercksen"
date: "Last compiled on `r format(Sys.time())`"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: inline
params:
  FCutoff:
    label: cutoff for the log2FoldChange
    value: 1
  pCutoff:
    label: "cutoff for the adjusted p-Value"
    value: 0.01
  fgsea.maxSize:
    label: "parameter for `fgsea`: 'Maximal size of a gene set to test. All pathways above the threshold are excluded.'"
    value: 200
  reevaluate:
    label: Should all calculations and database lookups be done again or just e.g.
      graphics regenerated
    value: no
  condition_pal: !r c("WT"= "#00C3C6","KO"= "#FF6C67")
  tissue_pal: !r c(gastroc = "orange", soleus="purple")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(fgsea)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(eulerr)
library(plotly, include.only = "ggplotly")
```

> insert code of fgsea or to load its files here
> …


# GO barplot
This was just an attempt to visualize the fgsea results.
Currently dotplots were taken as better visualization alternative.

```{r}
bd.df <- fgseaRes.combined %>%
  filter(diff.exp == "both down") %>%
  mutate(padj = padj.ga + padj.sol) %>% # just to sort
  arrange(padj) %>% 
  slice_head(n = 20) %>%
  select(-diff.exp, -padj) %>% 
 dplyr::rename(gastroc = padj.ga, soleus = padj.sol) %>% 
  tidyr::gather(key = "tissue", value = "p adj.", -pathway, -NES.ga, -NES.sol)

# convert data from wide to long format
df_long <- fgseaRes.combined %>%
  select(pathway, NES.ga, NES.sol) %>%
  dplyr::rename(gastroc = "NES.ga", soleus = "NES.sol") %>%
  tidyr::gather(key = "tissue", value = "NES", -pathway)

df_long <- select(bd.df, -NES.ga, -NES.sol) %>%
  merge(df_long, by = c("pathway", "tissue"))

# create grouped barplot
ggplot(df_long, aes(x = reorder(pathway, -NES), y = NES, fill = tissue)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme_classic() +
  xlab("Pathway") + ylab("NES") +
  scale_fill_manual(values = params$tissue_pal) +
  geom_text(aes(label = sprintf("%.2e", `p adj.`)), position = position_dodge(width = 0.9), vjust = +0.3, hjust = -1) +
  coord_flip()
```

```{r}
bd.df <- fgseaRes.combined %>%
  filter(diff.exp == "both up") %>%
  mutate(padj = padj.ga + padj.sol) %>% # just to sort
  arrange(padj) %>% 
  slice_head(n = 20) %>%
  select(-diff.exp, -padj) %>% 
  dplyr::rename(gastroc := padj.ga, soleus := padj.sol) %>% 
  tidyr::gather(key = "tissue", value = "p adj.", -pathway, -NES.ga, -NES.sol)

# convert data from wide to long format
df_long <- fgseaRes.combined %>% 
  select(pathway, NES.ga, NES.sol) %>% 
  dplyr::rename(gastroc := NES.ga, soleus := NES.sol) %>% 
  tidyr::gather(key = "tissue", value = "NES", -pathway)

df_long <- select(bd.df, -NES.ga, -NES.sol) %>%
  merge(df_long, by = c("pathway", "tissue"))



# create grouped barplot
ggplot(df_long, aes(
  x = reorder(pathway,+NES),
  y = NES,
  fill = tissue
)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_classic() +
  xlab("Pathway") + ylab("NES") +
  scale_fill_manual(values = params$tissue_pal) +
  geom_text(
    aes(label = sprintf("%.2e", `p adj.`)),
    position = position_dodge(width = 0.9),
    vjust = +0.3,
    hjust = +0.9
  ) +
  coord_flip()
```

```{r}
bd.df <- fgseaRes.combined %>%
  filter(diff.exp == "only soleus") %>%
  mutate(padj = padj.ga + padj.sol) %>% # just to sort
  select(pathway, NES.ga, NES.sol) %>% 
  arrange(NES.sol) %>% # TODO: ordering doesn't work!
  slice_head(n = 20)

# convert data from wide to long format
df_long <- tidyr::gather(bd.df, key = "tissue", value = "value", -pathway)

# create grouped barplot
ggplot(df_long, aes(x = pathway, y = value, fill = tissue)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme_classic() +
  xlab("Pathway") + ylab("NES") +
  scale_fill_manual(values = params$tissue_pal) +
  coord_flip()
```

#### cowplot

```{r}
library(ggplot2)
library(cowplot)

bd.df <- fgseaRes.combined %>%
  filter(diff.exp == "both up") 

# filter top 20 by adj. p-value
bd.df <- bd.df %>%
  mutate(padj = padj.ga + padj.sol) %>% # just to sort
  arrange(padj) %>% 
  slice_head(n = 20) %>%
  select(-diff.exp, -padj)

# prepare df for barplot (convert data from wide to long format)
df_long <- bd.df %>% 
  select(pathway, NES.ga, NES.sol) %>% 
  rename(gastroc := NES.ga, soleus := NES.sol) %>% 
  tidyr::gather(key = "tissue", value = "NES", -pathway)

# create the left panel with the bar plot and labels
bar_plot <- ggplot(df_long, aes(x = pathway, y = NES, fill = tissue)) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Pathway") +
  ylab("NES") +
  theme_classic() +
  theme(panel.grid = element_blank()) + 
  scale_fill_manual(values = params$tissue_pal) +
  coord_flip()

# create the right panel with the p-values
pval_plot <- ggplot(bd.df, aes(x = pathway, y = "")) +
  geom_text(aes(label = paste0(
    sprintf("%.2e", padj.ga), "\n", sprintf("%.2e", padj.sol)
  )), size = 3) +
  xlab("") + 
  ylab("p adj.") +
  theme_minimal() +
  coord_flip() +
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_blank(), # pathway names
  )

combined_plt <- cowplot::plot_grid(bar_plot, pval_plot, ncol = 2, align = "h", axis ="h")
# try parameter axis = c("l","tb",...)


# create the legend for the left plot
legend1 <- get_legend(bar_plot)
legend_plot <- draw_plot(legend1)

# combine the two plots using cowplot
cowplot::plot_grid(bar_plot, pval_plot, legend1, ncol = 3, align = "h", axis = "tb")# , rel_widths = c(10, 1.5, 1))

```

